FROM ghcr.io/rust-lang/crates-build-env/linux

ENV PATH=/root/.cargo/bin:$PATH
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | \
    sh -s -- --default-toolchain=nightly --component=rust-src --profile=minimal -y && \
    cargo install --git https://github.com/saethlin/miri-tools cargo-download

RUN apt-get update && \
    apt-get install -y clang lld expect && \
    rm -rf /var/lib/apt/lists/*

COPY config.toml /root/.cargo/config.toml

COPY get-args.py /root/
COPY run-asan.sh /root/run.sh

ENV RUSTFLAGS="-Zsanitizer=address --cap-lints=allow -Zrandomize-layout -Copt-level=0 -Cdebuginfo=1 -Zvalidate-mir"
ENV RUSTDOCFLAGS=$RUSTFLAGS
ENV ASAN_OPTIONS=detect_stack_use_after_return=true:allocator_may_return_null=1:detect_invalid_pointer_pairs=2
ENV CARGO_INCREMENTAL=0
ENV RUST_BACKTRACE=1

ENTRYPOINT ["bash", "/root/run.sh"]
