FROM ghcr.io/rust-lang/crates-build-env/linux

ENV PATH=/root/.cargo/bin:$PATH
ENV TOOLCHAIN=nightly

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | \
    sh -s -- --default-toolchain=nightly --component=miri --component=rust-src --profile=minimal -y && \
    cargo install --git https://github.com/saethlin/miri-tools cargo-download inapty get-args && \
    cargo install cargo-nextest

COPY nextest.toml /root/.cargo/

COPY run-miri.sh /root/run.sh

ENV RUSTFLAGS="--cap-lints=allow -Zrandomize-layout -Copt-level=0 -Cdebuginfo=0 -Zvalidate-mir"
ENV RUSTDOCFLAGS=$RUSTFLAGS
ENV MIRIFLAGS="-Zmiri-disable-isolation -Zmiri-ignore-leaks -Zmiri-panic-on-unsupported"
ENV CARGO_INCREMENTAL=0
ENV RUST_BACKTRACE=1

RUN cargo +nightly miri setup

ENTRYPOINT ["bash", "/root/run.sh"]
