[package]
name = "cargo-download"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2", features = ["derive"] }
ureq = "2.5"
tar = "0.4"
flate2 = "1"
