on:
  push:
    branches:
      - main
  pull_request:
    merge_group:
    branches:
      - main

name: CI

jobs:
  suite_matrix:
    strategy:
      matrix:
        suite: [style, check, build, miri, asan, fuzz]
    runs-on: ubuntu-latest
    name: ${{ matrix.suite }}
    steps:
      - uses: actions/checkout@v4
      - name: Rustup
        run: |
          rustup self update
          rustup default stable
          rustup update
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/bin/cargo-fuzz
            ~/.cargo/.crates2.json
            ~/.cargo/.crates.toml
            ~/.cargo/.global-cache
            ~/.cargo/.package-cache
            ~/.cargo/.package-cache-mutate
            ~/.cargo/.rustc_info.json
            target/
          key: ${{ runner.os }}-${{ matrix.suite }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-$(rustc --version)
      - name: Run
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: -Cdebuginfo=0
        run: ./ci.sh ${{ matrix.suite }}
