on:
  push:
    branches:
      - main
  pull_request:
    merge_group:
    branches:
      - main

name: CI

jobs:
  suite_matrix:
    strategy:
      matrix:
        suite: [style, check, build, miri, asan, fuzz]
    runs-on: ubuntu-latest
    name: ${{ matrix.suite }}
    steps:
      - uses: actions/checkout@v4
      - name: Rustup
        run: |
          rustup self update
          rustup default stable
          rustup update
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/bin/cargo-fuzz
            ~/.cargo/.crates2.json
            ~/.cargo/.crates.toml
            ~/.cargo/.global-cache
            ~/.cargo/.package-cache
            ~/.cargo/.package-cache-mutate
            ~/.cargo/.rustc_info.json
            target/
          key: ${{ runner.os }}-${{ matrix.suite }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-$(rustc --version)
      - name: Run
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: -Cdebuginfo=0
        run: |
          df -h
          du -h / | sort -h | tail
          echo "::group::Install dependencies"
          set -o pipefail
          CARGO_TARGET_DIR=target cargo install htmlpty --locked --path htmlpty
          set +e
          echo "::endgroup"
          htmlpty bash ci.sh ${{ matrix.suite }} 2> output.html
          FAILED=$?
          aws s3 cp --content-type "text/html;charset=utf-8" output.html s3://miri-bot-dev/${GITHUB_REPOSITORY}/${GITHUB_RUN_ID}/${{ matrix.suite }}.html
          LOG_URL=https://miri-bot-dev.s3.amazonaws.com/${GITHUB_REPOSITORY}/${GITHUB_RUN_ID}/${{ matrix.suite }}.html
          if [ $FAILED -ne 0 ]
          then
            curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.github_token }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                ${{ github.event.pull_request.comments_url }} \
                -d "{\"body\":\"$LOG_URL\"}"
          fi
          exit $FAILED
