on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: CI

jobs:
  style:
    runs-on: ubuntu-latest
    name: Style Checks
    steps:
      - uses: actions/checkout@v3
      - name: Install toolchain
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Style
        run: |
          cargo fmt --check
          cargo clippy -- -Dclippy::all

  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v3
      - name: Install toolchain
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Run
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          cargo run -- sync --tool=miri --bucket=miri-bot-dev
          cargo run -- run --tool=miri --bucket=miri-bot-dev --crate-list=ci-crates
          cargo run -- sync --tool=asan --bucket=miri-bot-dev
          cargo run -- run --tool=asan --bucket=miri-bot-dev --crate-list=ci-crates
          cargo run -- sync --tool=build --bucket=miri-bot-dev
          cargo run -- run --tool=build --bucket=miri-bot-dev --crate-list=ci-crates
