on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: CI

jobs:
  suite_matrix:
    strategy:
      matrix:
        suite: [style, check, build, miri, asan, fuzz]
    runs-on: ubuntu-latest
    name: Test ${{ matrix.suite }}
    steps:
      - uses: actions/checkout@v3
      - name: Run
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          echo "::group::Install dependencies"
          cargo install ansi-to-html inapty --locked --git https://github.com/saethlin/miri-tools
          echo "::endgroup"
          inapty bash ci.sh ${{ matrix.suite }} | tee /dev/stderr 2> >(ansi-to-html > output.html)
          aws s3 cp output.html s3://miri-bot-dev/${GITHUB_REPOSITORY}/${GITHUB_RUN_ID}/${{ matrix.suite }}.html
