on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: CI

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build
        run: cargo build

      - name: Style
        run: |
          cargo fmt --check
          cargo clippy -- -Dclippy::all

      - name: Run
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cargo run -- sync --tool=miri --bucket=miri-bot-dev
          cargo run -- run --tool=miri --crates=10 --bucket=miri-bot-dev
          cargo run -- sync --tool=miri --bucket=miri-bot-dev
          cargo run -- run --tool=asan --crates=10 --bucket=miri-bot-dev
          cargo run -- sync --tool=asan --bucket=miri-bot-dev
