on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: CI

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build
        run: cargo build

      - name: Formatting
        run: |
          cargo fmt --check
          cargo clippy -- -Dclippy::all

      - name: Run
        run: |
          cargo run -- --crates=10
          cargo run --bin render
          cargo run --bin uploader -- --help
